#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Il lotto di voci di Ferri (1889) che entra nei dati, scelto a mano.

Questo file e' la lista, non il procedimento. Il procedimento e' in
`estrai_ferri.py` (che stacca le voci dall'OCR) e in `filtra_candidati.py`
(butta via quello che non si legge). Qui si decide, e la decisione e' di una
persona che ha guardato la voce una per una.

Ogni riga e' una tupla:

    (chiave, ferrarese, italiano, campo, attendibilita, nota)

`chiave`       come la voce compare nel file dei candidati, serve a trovare
               il numero di pagina. Non finisce nei dati.
`ferrarese`    come si scrive nel glossario: scelta dal lettore, con
               l'apostrofo normale e le sillabe staccate.
`italiano`     il gloss del Ferri, ripulito dai pezzi che l'OCR ha mangiato.
`campo`        la categoria funzionale: `locuzione`, `modo di dire`, `avverbio`,
               `sostantivo`, `aggettivo`, `esclamazione`, `gioco`, `proverbio`.
`attendibilita`  `D` quando la scrittura e' certa, `I` quando l'OCR ha reso
               solo una parte e la divisione delle parole e' congetturale.
               `D` con `da_verificare` falso e `I` con `da_verificare` vero
               non e' un compromesso: e' la differenza fra quello che si puo'
               controllare aprendo il libro e quello che no.
`nota`         quello che il glossario non ha un campo dove mettere.

Il gloss del Ferri e' italiano del 1889, non italiano di oggi: «brisa», «sarvamento»,
«ciclone». Non si corregge perche' correggerlo sarebbe tradurre la fonte invece
di riportarla; il rimando a oggi e' nelle coppie e nel gioco.
"""

from __future__ import annotations

# (chiave, ferrarese, italiano, campo, attendibilita, nota)
LOCUZIONI = [
    # --- A ---
    ("A badaréla", "a bada", "con calma, senza fretta", "locuzione", "D", "Il Ferri dà due forme per la stessa resa, «a bada» e «a badalucco».", ["a badalucco"]),
    ("A bissabuò", "a bissabuò", "a bisciabba, a zig zag", "avverbio", "D", "Il gloss porta anche la forma italiana «a bisciabba»."),
    ("A bizéf", "a bizzeffe", "a bizzeffe, a iosa", "avverbio", "D", "", ["a iosa"]),
    ("A bótafass", "a bottafàsso", "a catafascio, alla rinfusa", "avverbio", "D", ""),
    ("A brazz avèrti", "a brazz avèrti", "a braccia aperte", "locuzione", "D", ""),
    ("A cavai", "a cavai", "a cavallo", "avverbio", "D", ""),
    ("A crepapanzza", "a crepapànza", "a crepapelle, a crepapancia", "avverbio", "D", ""),
    ("Adasi adasi", "adasì adasi", "lemme lemme, lentamente", "avverbio", "D", ""),
    ("Ad bót", "ad bót", "quasi", "avverbio", "D", ""),
    ("Ad corsa", "ad corsa", "di corsa", "avverbio", "D", ""),
    ("Adéss dèss", "adéss dèss", "a momenti, quasi", "avverbio", "D", ""),
    ("Ad pianta", "ad pianta", "di pianta", "avverbio", "D", ""),
    ("Ad sota", "ad sòta", "disotto, di sotto", "avverbio", "D", ""),
    ("Ad travérss", "ad travérss", "di traverso", "avverbio", "D", ""),
    ("Ad zzerta", "ad zzerta", "di certo, certamente", "avverbio", "D", ""),
    ("Ala del cappello", "ala del capèl", "falda, e tesa se e' rovesciata in alto", "locuzione", "D", ""),
    ("Ala dorsale", "ala dorsale", "quella vicino alla schiena", "locuzione", "D", ""),
    ("Ala mata", "ala mata", "all'impazzata", "avverbio", "D", ""),
    ("Ala pari", "ala pari", "alla pari", "avverbio", "D", ""),
    ("Al' impàr", "al' impàr", "alla pari", "avverbio", "D", "Il Ferri dà due voci per la stessa resa: «al' impar» e «andàr al' impar»."),
    ("Andar al' impar", "andar al' impar", "andare di pari passo, andare di conserva", "avverbio", "D", ""),
    ("Al ingross", "al ingross", "all'ingrosso", "avverbio", "D", ""),
    ("Al óra", "al óra", "all'ombra", "avverbio", "D", ""),
    ("Alta dal pozz", "alta dal pozz", "parapetto, spónda", "locuzione", "D", ""),
    ("Alvar ad pes", "alvar ad pes", "levare di soppeso", "modo di dire", "D", ""),
    ("A malincuòr", "a malincuòr", "malvolentieri, a malincuore", "avverbio", "D", ""),
    ("A man a zunt", "a man a zunt", "a mani giunte", "avverbio", "D", ""),
    ("A man salva", "a man salva", "sicuramente, a man salva", "avverbio", "D", ""),
    ("A mena dida", "a mena dida", "a menadito, benissimo", "avverbio", "D", ""),
    ("Ancora dal co", "ancora dal co", "anche adesso, tuttora", "avverbio", "D", ""),
    ("Ammazzars da par lor aposta", "ammazzàrs da par lor apòsta", "suicidarsi", "locuzione", "D", ""),
    ("A pie cavai", "a pie cavai", "sotto gli occhi, impunemente", "avverbio", "D", ""),
    ("A pòch a pòch", "a pòch a pòch", "a poco a poco", "avverbio", "D", ""),
    ("A pósta", "a pósta", "a bella posta, pensatamente", "avverbio", "D", ""),
    ("Arbàtar il cusdur", "arbàtar il cusdur", "rimboccare", "modo di dire", "D", ""),
    ("Arbàtar la porta", "arbàtar la porta", "socchiudere", "modo di dire", "D", ""),
    ("Arbàtar il vid", "arbàtar il vid", "propagginare", "modo di dire", "D", ""),
    ("Arent al mur", "arent al mur", "rasente al muro", "avverbio", "D", ""),
    ("Arma da mort", "arma da mort", "cartello", "locuzione", "D", ""),
    ("Arma e létra", "arma e létra", "santi e palle", "gioco", "D", "Specie di gioco: il Ferri la registra senza spiegarla."),
    ("A ròta d col", "a ròta d col", "a rompicollo", "avverbio", "D", ""),
    ("A sangv e gola", "a sangv e gola", "indefessamente", "avverbio", "D", ""),
    ("A spina ad pèss", "a spina ad pèss", "a spina di pesce", "avverbio", "D", ""),
    ("A spjzzgót", "a spizzigót", "a spizzico", "avverbio", "D", ""),
    ("Ass da sculàr i piat", "ass da sculàr i piat", "scolatoio", "locuzione", "D", ""),
    ("A uf", "a uf", "a macca, a ufo", "avverbio", "D", ""),
    ("A un dipréss", "a un dipréss", "circa, all'incirca", "avverbio", "D", ""),
    ("A un tant al brazz", "a un tant al brazz", "a casaccio, a fanfara, inconsideratamente", "avverbio", "D", ""),
    ("Ava salvàdga", "ava salvàdga", "pecchione", "sostantivo", "D", ""),
    ("Avèrn ad grazzia", "avèrn ad grazzia", "avere la sua gatta da pelare", "modo di dire", "D", "Il gloss porta anche «averne di gatti», che e' la forma letteraria del proverbio italiano."),
    ("A vizzi", "a vizzi", "calcolatamente, a bella posta", "avverbio", "D", ""),
    ("Azzetar 'na sfida", "azzetar 'na sfida", "raccogliere il guanto", "modo di dire", "D", ""),
    ("Andar a bagnòl", "andar a bagnòl", "andare in guazzo", "modo di dire", "D", ""),
    ("Ad bùss in bàss", "ad bùss in bàss", "di palo in frasca, d'alto in basso", "avverbio", "D", ""),
    ("Andar in béstia", "andar in béstia", "imbestialire, uscire dai gangheri", "modo di dire", "D", ""),
    ("Aver i calzzit a cagarèla", "aver i calzzit a cagarèla", "averli a bracialoni", "modo di dire", "D", ""),
    ("Al cantar dal gali", "al cantar dal gal", "cuccurrire", "modo di dire", "D", ""),
    ("A caplà m avv", "a caplà", "a iosa, a macca", "avverbio", "D", ""),
    ("Ad prim colp", "ad prim colp", "di coltà", "avverbio", "D", ""),
    ("Al stricàr dj cont", "al stricàr dj cont", "per ultimo, finalmente", "avverbio", "D", ""),
    ("Ad còrssa", "ad còrssa", "di corsa", "avverbio", "D", ""),
    ("A CUI busùn", "a cui busùn", "boccone e bocconi", "sostantivo", "D", ""),
    ("Ala cùrta", "ala cùrta", "alle corti", "avverbio", "D", ""),
    ("Ad tut i dì", "ad tut i dì", "quotidiano", "aggettivo", "D", "Le «i dì» con l'articolo sono la parte ferrarese: l'italiano direbbe «di ogni giorno»."),
    # --- B ---
    ("Banchèt da spus", "banchèt da spus", "inginocchiatoio", "locuzione", "D", ""),
    ("Bàtar il munèd", "bàtar il munèd", "coniare", "modo di dire", "D", ""),
    ("Bàtar al furment", "bàtar al furmènt", "trebbiare", "modo di dire", "D", ""),
    ("Bianch di oc", "bianch di oc", "albùgine", "locuzione", "D", ""),
    ("Blanch' di' ov", "blanch' di' ov", "albume", "locuzione", "D", ""),
    ("Bigàt da seda", "bigàt da seda", "filugello, baco da seta", "locuzione", "D", ""),
    ("Bigul dia fibia", "bigul dia fibia", "ardiglione", "locuzione", "I", "La divisione delle parole e' congetturale: l'OCR ha reso «bigul» e «fibia» senza capire che sono due."),
    ("Boca da ridar", "boca da ridar", "sorriso", "locuzione", "D", ""),
    ("Bon in tal castigar", "bon in tal castigar", "clemente", "aggettivo", "D", ""),
    ("Brancar coi dent", "brancar coi dent", "addentare, azzannare", "modo di dire", "D", ""),
    ("Brasa dal togh", "brasa dal togh", "bragia", "locuzione", "D", ""),
    ("Brasa dal stupin", "brasa dal stupin", "fungo, moccolaio", "locuzione", "D", ""),
    ("Bucai o bucalin", "bucai o bucalìn", "vaso da notte, pitale, orinale", "sostantivo", "D", ""),
    ("Bucardin dia cà", "bucardìn dia cà", "feritoia", "locuzione", "D", ""),
    ("Bucarin o bucaròl", "bucarìn o bucaròl", "setola", "sostantivo", "D", ""),
    ("Bùiar a onda", "bùiar a ónda", "bollire a ricorsóio, bollire a scroscio", "locuzione", "D", ""),
    ("Buia d erba", "buia d' èrba", "cespo", "locuzione", "D", ""),
    ("Bulìn da Jétar", "bulìn da jétar", "névola", "sostantivo", "D", ""),
    ("Brisa bunì", "brisa bunì", "immaturo", "aggettivo", "D", ""),
    ("Brisa cumpatibil", "brisa cumpatìbil", "incompatibile", "aggettivo", "D", ""),
    ("Buntà granda", "buntà granda", "bontà, buon'anima", "sostantivo", "D", ""),
    ("Buntà in tal castigar", "buntà in tal castigar", "clemenza", "sostantivo", "D", ""),
    ("Brustlà dal varol", "brustlà dal varol", "butterato", "aggettivo", "D", ""),
    ("Brustlàr al caffè", "brustlàr al caffè", "tostare", "verbo", "D", ""),
    ("Brustlàr la pulènta", "brustlàr la pulènta", "abbrustolire", "verbo", "D", ""),
    ("Brustlàrss al sòl", "brustlàrss al sòl", "abbronzare", "verbo", "D", ""),
    ("Bona lana", "bona lana", "persona scaltra e maliziosa; donna scodala", "modo di dire", "D", ""),
    ("Bona scavzzadóra", "bona scavzzadóra", "chi mangia molto (pacchione, mangione)", "modo di dire", "D", ""),
    ("Butàr zó un da cavai", "butàr zó un da cavai", "scavalcare", "modo di dire", "D", ""),
    ("Butàr fora", "butàr fora", "vomitare, eruttare", "verbo", "D", ""),
    ("Butàr a cui in su", "butàr a cui in su", "sconvolgere", "modo di dire", "D", ""),
    ("Brusàr da la sé", "brusàr da la sé", "allampare", "verbo", "D", ""),
    ("Biss scurzzòn", "biss scurzòn", "scorzone", "sostantivo", "D", ""),
    # --- C ---
    ("Con abilità", "con abilità", "abilmente", "avverbio", "D", ""),
    ("Con afann", "con afann", "affannatamente", "avverbio", "D", ""),
    ("Con agevulèzza", "con agevulèzza", "agevolmente", "avverbio", "D", ""),
    ("Con amicizzia", "con amicizzia", "amichevolmente", "avverbio", "D", ""),
    ("Con dr ansietà", "con ansietà", "ansiosamente", "avverbio", "D", ""),
    ("Con aruganza", "con aruganza", "arrogantemente", "avverbio", "D", ""),
    ("Con asprezza", "con asprezza", "aspramente", "avverbio", "D", ""),
    ("Con astùzzia", "con astùzzia", "astutamente", "avverbio", "D", ""),
    ("Con audacia", "con audacia", "audacemente", "avverbio", "D", ""),
    ("Con avidità", "con avidità", "avidamente", "avverbio", "D", ""),
    ("Coup bassezza", "con bassezza", "bassamente", "avverbio", "D", ""),
    ("Con armonia", "con armonia", "armonicamente", "avverbio", "D", ""),
    ("Cantar T antifuna", "cantar l'antifuna", "parlare liberamente; dire il fatto suo", "modo di dire", "D", ""),
    ("Cavar il brasòl", "cavar il brasòl", "sfrittellare", "verbo", "D", ""),
    ("Còrar a bria vèrta", "còrar a bria vèrta", "correre a briglia sciolta", "modo di dire", "D", ""),
    ("Cagar sul bulìn", "cagar sul bulìn", "mancare alla parola data", "modo di dire", "D", ""),
    ("Cagàrss adòss dala cuntantezza", "cagàrss adòss dala cuntantèzza", "imbietolire, imbrogiottirsi", "verbo", "D", ""),
    ("Cagar i stupin", "cagar i stupin", "pagare dopo aver goduto", "modo di dire", "D", "Il Ferri parafrasa: «cacar le lische dopo aver mangiato i pesci»."),
    ("Cagar sul fugòn", "cagar sul fugòn", "radersi delle altrui minacce", "modo di dire", "D", ""),
    ("Cantar in falsèt", "cantar in falsèt", "cantare in falsetto", "locuzione", "D", ""),
    ("Cassòn da bigàt", "cassòn da bigàt", "donna oltremodo grassa", "locuzione", "D", ""),
    # --- D ---
    ("D' arvérss", "d' arvérss", "a rovescio, per rovescio", "avverbio", "D", ""),
    ("Dar al bcon", "dar al bcon", "dare l'ingoffo; corrompere con danaro", "modo di dire", "D", ""),
    ("Da pari e pari", "da pari e pari", "da pari a pari", "avverbio", "D", ""),
    ("Danars par riuscir in cvèl", "danàrs par riuscir in cvèl", "arrabattarsi, affaticarsi", "verbo", "D", ""),
    ("Dar man", "dar man", "aiutare", "verbo", "D", ""),
    ("Dar sòta", "dar sòta", "inzigare, spalleggiare", "verbo", "D", ""),
    ("Dar aria", "dar aria", "arieggiare", "verbo", "D", ""),
    ("Dar la biàca", "dar la biàca", "imbiaccare", "verbo", "D", ""),
    ("Dvantar bianch dala paura", "dventàr bianch dala paura", "impallidire", "verbo", "D", ""),
    ("Dvantàr bis", "dventàr bis", "imbigiare", "verbo", "D", ""),
    ("Dvantàr bolss", "dventàr bolss", "imbolsire", "verbo", "D", ""),
    ("Dar la bòsma", "dar la bòsma", "imbozzimare", "verbo", "D", ""),
    ("Dvantàr carbón", "dventàr carbón", "incarbonire", "verbo", "D", ""),
    ("Dar na culata", "dar na culata", "mazzacuffare, battere una culatta", "verbo", "D", ""),
    ("Dar o tòrss cumià", "dar o tòrss cumià", "licenziare, accomiatare", "verbo", "D", ""),
    ("Dar in cóst", "dar in cóst", "urtare", "verbo", "D", ""),
    # --- E ---
    ("Essar fora d' ara", "essar fora d' ara", "essere rovinato, non poter piu' nulla", "modo di dire", "D", ""),
    ("Essar ad larga", "essar ad largà", "essere rovinato, non poter piu' nulla", "modo di dire", "D", "Il Ferri registra la voce due volte, con due grafie diverse."),
    ("Essar al orba", "essar al orba", "essere al buio; menare le mani alla cieca", "modo di dire", "D", ""),
    ("Essar o gnir al salt", "essar o gnir al salt", "essere o venire in fregola", "modo di dire", "D", ""),
    ("Essar sènipar vie con la tèsta", "essar sènipar vie con la tèsta", "avere il cervello a ciabatta", "modo di dire", "D", ""),
    ("Essar in zir", "essar in zir", "andare attorno; circolare", "verbo", "D", ""),
    ("Essar in fàli", "essar in fàli", "fagliare", "verbo", "D", ""),
    ("Ered insiem", "erèd insiem", "coerede", "sostantivo", "D", ""),
    # --- F ---
    ("Far baldoria", "far baldoria", "fare baldoria, darsi bel tempo", "locuzione", "D", ""),
    ("Far al cai", "far al cai", "incallire", "verbo", "D", ""),
    ("Far dj cònt", "far dj cònt", "conteggiare, calcolare", "verbo", "D", ""),
    ("Far dj cònt in aria", "far dj cònt in aria", "fantasticare, abbacar di zeri", "modo di dire", "D", ""),
    ("Far la còrt", "far la còrt", "corteggiare", "verbo", "D", ""),
    ("Far il còs con cunfidenza", "far il còs con cunfidenza", "fare a fidanza", "modo di dire", "D", ""),
    ("Far al diàvul e quàtar", "far al diàvul e quàtar", "arrabattarsi per avere una cosa", "modo di dire", "D", ""),
    ("Far alt e bass una cosa", "far alt e bass una cosa", "manare, guastare, rovinare", "modo di dire", "D", ""),
    ("Fare a nocino", "far a nocino", "giocare con le noci", "gioco", "D", ""),
    # --- G ---
    ("Gagà spudà", "gagà spudà", "tale quale", "locuzione", "D", ""),
    ("Gabanina sf o gabanin sm", "gabanina", "sacchetto, gabbanetto", "sostantivo", "D",
     "Il Ferri dà le due forme nella stessa voce, una diminutiva e l'altra.", ["gabanin"]),
    ("Gamba ramada", "gamba ramada", "gamba arcata", "locuzione", "D", ""),
    ("Garzón ad butéga", "garzón ad butéga", "fattorino", "sostantivo", "D", ""),
    ("Gat ad piomb", "gat ad piomb", "piombone (persona lenta)", "sostantivo", "D", ""),
    ("Glori giori", "glori giori", "mogio mogio", "avverbio", "D", ""),
    ("Gnient afàt", "gnient afàt", "per niente, per nulla", "avverbio", "D", ""),
    ("Gnir a la pél", "gnir a la pèl", "arrivare alle spalle", "locuzione", "D", ""),
    # --- L ---
    ("La bissa s arvòlta al zzarlatàn", "la bissa s'arvòlta al zzarlatàn", "la biscia becca il ciarlatano", "proverbio", "D", ""),
    ("Lavurar sott'acqua", "lavurar sott'acqua", "tramare, subdoleggiare", "modo di dire", "D", ""),
    ("Lavurar ad schina", "lavurar ad schina", "bordare", "verbo", "D", ""),
    ("L ucasion fa T om làdar", "l'ucasion fa l'om làdar", "al infornare il pan si fa goloso", "proverbio", "D", ""),
    ("Ligàr con un làzz", "ligàr con un làzz", "incapestrare", "verbo", "D", ""),
    ("Litgàr va e vr", "litgàr", "litigare, altercare", "verbo", "D", ""),
    ("Ludar molt", "ludar molt", "encomiare", "verbo", "D", ""),
    # --- M ---
    ("Metar a fen il besti", "metàr a fen il bèsti", "affienare", "verbo", "D", ""),
    ("Metarss d inteligenzza", "metàrss d'inteligenza", "concordare", "verbo", "D", ""),
    ("Metar in dj fastìdi", "metàr in dj fastìdi", "mettere nelle peste", "modo di dire", "D", ""),
    ("Mètar il bésti a fòja", "mètar il bèsti a fòja", "affogliare", "verbo", "D", ""),
    ("Mètar in fila", "mètar in fila", "allineare", "verbo", "D", ""),
    ("Mandar o andar in frasca", "mandar o andar in frasca", "mandare o andare al bosco", "modo di dire", "D", ""),
    ("Magnificamént ben", "magnificamént ben", "ottimamente", "avverbio", "D", ""),
    ("Maiéta dim", "maiéta", "maglietta", "sostantivo", "D", ""),
    ("Mal eh a s' tàca", "mal eh a s' tàca", "epidemia, male contagioso", "sostantivo", "D", ""),
    # --- N ---
    ("Nas vinca", "nas vìnca", "naso aquilino", "locuzione", "D", ""),
    ("Nas brugnuclòs", "nas brugnuclòs", "naso bitorzoluto", "locuzione", "D", ""),
    ("Nas a funzòla", "nas a funzòla", "naso spugnoso", "locuzione", "D", ""),
    ("Nas incassa", "nas incassa", "naso intasato", "locuzione", "D", ""),
    ("Nas schizz", "nas schizz", "naso camuso", "locuzione", "D", ""),
    ("Net net", "net net", "nettamente", "avverbio", "D", ""),
    ("Nunon dal nunon", "nunòn dal nunòn", "arcangelo", "sostantivo", "D", ""),
    ("Nud e crud", "nud e crud", "poverissimo, pezzente", "avverbio", "D", ""),
    ("Nat e spudà", "nat e spudà", "nato e sputato, simigliantissimo", "avverbio", "D", ""),
    # --- O ---
    ("Oca d Àvril", "oca d'avril", "pesce d'aprile", "locuzione", "D", ""),
    ("O dio", "o dio", "ahime'", "esclamazione", "D", ""),
    ("Oc drit", "oc drit", "coccio (figlio prediletto)", "sostantivo", "D", ""),
    ("Oc in dentar", "oc in dentar", "occhio infossato", "locuzione", "D", ""),
    ("Om da pòch", "om da pòch", "avaro", "sostantivo", "D", ""),
    ("Om senza guài", "om senza guài", "pensierato", "aggettivo", "D", ""),
    ("Ogni sira", "ogni sira", "seralmente", "avverbio", "D", ""),
    ("Ov scuvazzà", "ov scuvazzà", "barlaccio", "aggettivo", "D", ""),
    ("Ov stanti", "ov stanti", "stantio", "aggettivo", "D", ""),
    # --- P ---
    ("Per morire", "per morire", "andare a maravalle", "modo di dire", "D", ""),
    ("Per fare attenzione", "per fare attenzion", "abbadare, por mente", "verbo", "D", ""),
    ("Per sgradevole odore", "per sgradevole odore", "puzzo, fetore", "sostantivo", "D", ""),
    ("Per grosso errore", "per grosso errore", "bestialita', corbelleria", "sostantivo", "D", ""),
    ("Per buon guadagno", "per buon guadagn", "passione (vita comoda)", "sostantivo", "D", ""),
    ("Per cosa malfatta", "per cosa malfatta", "corbelleria, buscherata", "sostantivo", "D", ""),
    ("Per molta istruzione", "per molta istruzzion", "sapienza, erudizione", "sostantivo", "D", ""),
    # --- Q ---
    ("Quaciàr ad còdagh", "quaciàr ad còdagh", "piotare", "verbo", "D", ""),
    ("Quaciàr il scarànn", "quaciàr il scarànn", "impagliare", "verbo", "D", ""),
    ("Quietar un inrabì", "quietar un inrabì", "abbonacciare, abbonire", "verbo", "D", ""),
    ("Q a la sorda", "a la sorda", "all'improvviso, alla sordina", "avverbio", "D", ""),
    # --- R ---
    ("Rompar T amicizzia", "rompar l'amicizzia", "rompere il ruscellino", "locuzione", "D", ""),
    ("Ranzzgòr vn", "ranzògòr", "bruciare, cuocere, friggere", "verbo", "D", ""),
    ("Rèndar mal par ben", "rèndar mal par ben", "pagare di mala moneta", "modo di dire", "D", ""),
    ("Rabirss da bòn", "rabìrss da bòn", "arrovellarsi", "verbo", "D", ""),
    ("Rabirss con rasòn", "rabìrss con rasòn", "indignarsi", "verbo", "D", ""),
    ("Rassìna da bòtt", "rassina da bòtt", "rasiera", "sostantivo", "D", ""),
]